CREATE DATABASE JOBSEEKER
USE JOBSEEKER
CREATE TABLE JOBEMPLOYEE(EMPNO BIGINT,ENAME VARCHAR(50),DEPTNO BIGINT,JOB VARCHAR(10),HIREDATE DATETIME)
CREATE TABLE DEPT(DEPNO BIGINT,DNAME VARCHAR(20),LOC VARCHAR(20))


CREATE TABLE TS_COMPANY_MASTER(ID BIGINT,NAME VARCHAR(25),REMARKS BIGINT)
CREATE TABLE TS_GROUP_MASTER(ID BIGINT,NAME VARCHAR(25),REMARKS BIGINT)
CREATE TABLE TS_ITEM_MASTER(ID BIGINT,NAME VARCHAR(25),COMPANY_ID BIGINT,GROUP_ID BIGINT,RATE BIGINT,REMARKS BIGINT)
CREATE TABLE TS_PURCHASE_HEADER(ID INT,PURCHASE_NO BIGINT,TRNS_DATE DATETIME,TOTAL BIGINT,REMARKS BIGINT)
CREATE TABLE TS_PURCHASE_DETAILS(ID INT ,HEADER_ID BIGINT,SL_NO INT, ITEM_ID BIGINT,QTY BIGINT,RATE BIGINT,AMOUNT INT)


INSERT INTO TS_COMPANY_MASTER (ID,NAME,REMARKS) VALUES(1,'P&G','')
INSERT INTO TS_COMPANY_MASTER(ID,NAME,REMARKS)VALUES(2,'XENICAL','')
INSERT INTO TS_COMPANY_MASTER(ID,NAME,REMARKS)VALUES(3,'J&J','')
INSERT INTO TS_COMPANY_MASTER(ID,NAME,REMARKS)VALUES(4,'JAC','')

INSERT INTO TS_GROUP_MASTER(ID,NAME,REMARKS)VALUES(1,'INHALER','')
INSERT INTO TS_GROUP_MASTER(ID,NAME,REMARKS)VALUES(2,'DROPS','')
INSERT INTO TS_GROUP_MASTER(ID,NAME,REMARKS)VALUES(3,'POWDER','')
INSERT INTO TS_GROUP_MASTER(ID,NAME,REMARKS)VALUES(4,'OINTMENT','')

DELETE FROM TS_COMPANY_MASTER WHERE ID=1
DELETE FROM TS_GROUP_MASTER WHERE NAME='INHALER'


UPDATE TS_COMPANY_MASTER SET NAME='P&G' WHERE ID=2


UPDATE JOBEMPLOYEE SET ENAME =(SELECT ENAME FROM JOBEMPLOYEE WHERE EMPNO=2000)



DROP TABLE TS_COMPANY_MASTER

ALTER TABLE TS_COMPANY_MASTER ADD AGE INT
ALTER TABLE TS_GROUP_MASTER ADD NEW_COLUM  BIGINT
ALTER TABLE TS_ITEM_MASTER ALTER COLUMN NAME VARCHAR(30)


